#!/bin/sh

set -e
set -x

cd sandbox
cabal sandbox hc-pkg unregister postgresql-native-connection || true
cabal sandbox hc-pkg unregister postgresql-native-openssl || true
cd ..

cd postgresql-native-core
cabal clean
cabal install --only-dependencies --enable-documentation --haddock-internal --haddock-hyperlink-source
cabal configure
cabal install --enable-documentation --haddock-internal --haddock-hyperlink-source
cd ..
cd postgresql-native-connection
cabal clean
cabal install --only-dependencies --enable-documentation --haddock-internal --haddock-hyperlink-source
cabal configure
cabal install --enable-documentation --haddock-internal --haddock-hyperlink-source
cd ..
cd postgresql-native-openssl
cabal clean
cabal install --only-dependencies --enable-documentation --haddock-internal --haddock-hyperlink-source
cabal configure
cabal install --enable-documentation --haddock-internal --haddock-hyperlink-source
cd ..
cd scratch
cabal clean
cabal configure
cabal build
cd ..
