#!/bin/sh

set -e

cd sandbox
cabal sandbox hc-pkg unregister postgresql-native-connection || true
cabal sandbox hc-pkg unregister postgresql-native-openssl || true
cd ..

cd postgresql-native-core
cabal clean
cabal configure
cabal install
cd ..
cd postgresql-native-connection
cabal clean
cabal configure
cabal install
cd ..
cd postgresql-native-openssl
cabal clean
cabal configure
cabal install
cd ..
cd scratch
cabal clean
cabal configure
cabal build
cd ..
